{"version":3,"file":"static/chunks/pages/_error-bd3084c6438b5fff.js","mappings":"qFACKA,OAAOC,SAAWD,OAAOC,UAAY,IAAIC,KAAK,CAC7C,UACA,WACE,OAAO,EAAQ,U,wGCiBjBC,EAAuBC,SAAAA,GAK3B,OAAO,SAACC,EAAAA,QAAkB,CAACC,WAAYF,EAAME,cAG/CH,EAAqBI,gBAAkB,W,OAAA,4BAAMC,G,iFAGrCC,EAAAA,EAAuCD,G,gCAGtCH,EAAAA,QAAAA,gBAAmCG,I,2DANCA,G,gCAAN,GASvC,c","sources":["webpack://_N_E/?5234","webpack://_N_E/./pages/_error.js"],"sourcesContent":["\n    (window.__NEXT_P = window.__NEXT_P || []).push([\n      \"/_error\",\n      function () {\n        return require(\"private-next-pages/_error.js\");\n      }\n    ]);\n    if(module.hot) {\n      module.hot.dispose(function () {\n        window.__NEXT_P.push([\"/_error\"])\n      });\n    }\n  ","/**\n * NOTE: This requires `@sentry/nextjs` version 7.3.0 or higher.\n *\n * NOTE: If using this with `next` version 12.2.0 or lower, uncomment the\n * penultimate line in `CustomErrorComponent`.\n *\n * This page is loaded by Nextjs:\n *  - on the server, when data-fetching methods throw or reject\n *  - on the client, when `getInitialProps` throws or rejects\n *  - on the client, when a React lifecycle method throws or rejects, and it's\n *    caught by the built-in Nextjs error boundary\n *\n * See:\n *  - https://nextjs.org/docs/basic-features/data-fetching/overview\n *  - https://nextjs.org/docs/api-reference/data-fetching/get-initial-props\n *  - https://reactjs.org/docs/error-boundaries.html\n */\n\nimport * as Sentry from '@sentry/nextjs';\nimport NextErrorComponent from 'next/error';\n\nconst CustomErrorComponent = props => {\n  // If you're using a Nextjs version prior to 12.2.1, uncomment this to\n  // compensate for https://github.com/vercel/next.js/issues/8592\n  // Sentry.captureUnderscoreErrorException(props);\n\n  return <NextErrorComponent statusCode={props.statusCode} />;\n};\n\nCustomErrorComponent.getInitialProps = async contextData => {\n  // In case this is running in a serverless function, await this in order to give Sentry\n  // time to send the error before the lambda exits\n  await Sentry.captureUnderscoreErrorException(contextData);\n\n  // This will contain the status code of the response\n  return NextErrorComponent.getInitialProps(contextData);\n};\n\nexport default CustomErrorComponent;\n"],"names":["window","__NEXT_P","push","CustomErrorComponent","props","NextErrorComponent","statusCode","getInitialProps","contextData","Sentry"],"sourceRoot":""}